version: "3"

# Use docker-compose-multiarch as the working directory while using this file!

services:
  lowkey-vault:
    container_name: docker-compose-multiarch-lowkey-vault
    image: nagyesta/lowkey-vault:2.5.6-ubi9-minimal
    ports:
      - "8443:8443"
    volumes:
      - example-import:/import/:rw
      - example-config:/config/:ro
    environment:
      # Set arguments for Lowkey Vault configuring key parameters, such as:
      # - setting the port we want to use: --server.port=8443
      # - overriding the key store type: --server.ssl.key-store-type=JKS
      # - overriding the key store path: --server.ssl.key-store=/config/cert.jks
      # - overriding the key store password: --server.ssl.key-store-password=password
      # - disable automatic vault creation: --LOWKEY_VAULT_NAMES=-
      # - turn off debug option controlling request logging: --LOWKEY_DEBUG_REQUEST_LOG=false
      # - specify the name of the import file: --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs
      # - defining the value of {{host}} placeholders in the import: --LOWKEY_IMPORT_TEMPLATE_HOST=localhost
      # - defining the value of {{port}} placeholders in the import: --LOWKEY_IMPORT_TEMPLATE_PORT=8443
      # More details at: https://github.com/nagyesta/lowkey-vault/tree/main/lowkey-vault-app#startup-parameters
      LOWKEY_ARGS: > 
        --server.port=8443
        --server.ssl.key-store-type=JKS 
        --server.ssl.key-store=/config/cert.jks 
        --server.ssl.key-store-password=password 
        --LOWKEY_VAULT_NAMES=- 
        --LOWKEY_DEBUG_REQUEST_LOG=false 
        --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs 
        --LOWKEY_IMPORT_TEMPLATE_HOST=localhost 
        --LOWKEY_IMPORT_TEMPLATE_PORT=8443
  assumed-identity:
    container_name: docker-compose-multiarch-assumed-identity
    image: nagyesta/assumed-identity:1.2.42
    ports:
      - "8080:8080"
    environment:
      # Set port number to the one we want to use on the host machine
      ASSUMED_ID_PORT: "8080"
volumes:
  # Create a volume, allowing us to share the backup file with the container by mounting it
  example-import:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      # set the ./import directory as volume root
      device: "$PWD/import"
  example-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      # set the ./config directory as volume root
      device: "$PWD/config"
