
name: Docker test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3.3.0
      with:
        go-version: '1.18.2'
    - name: Start Lowkey Vault using Docker compose
      run: |
        cd docker-compose
        docker-compose up -d
        sleep 5
        docker ps
    - name: Test with go
      run: |
        go test ./test -v
    - name: Stop container with compose
      if: always()
      run: |
        cd docker-compose
        docker-compose down
    - name: Start Lowkey Vault using Docker command
      run: |
        cd docker
        sh example.sh
        sleep 5
        docker ps
    - name: Test with go
      run: |
        go clean -testcache
        go test ./test -v
    - name: Stop container with command
      if: always()
      run: |
        docker stop lowkey-docker
