
name: Docker test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3
    - name: Set up Go
      uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
      with:
        go-version: '1.18.2'
    - name: Start Lowkey Vault using Docker compose
      run: |
        cd docker-compose
        docker-compose up -d
        sleep 5
        docker ps
    - name: Test with go
      run: |
        go test ./test -v
    - name: Stop container with compose
      if: always()
      run: |
        cd docker-compose
        docker-compose down
    - name: Start Lowkey Vault using Docker compose using multi-arch image
      run: |
        cd docker-compose-multiarch
        docker-compose up -d
        sleep 5
        docker ps
    - name: Test with go
      run: |
        go clean -testcache
        go test ./test -v
    - name: Stop container with compose
      if: always()
      run: |
        cd docker-compose-multiarch
        docker-compose down
    - name: Start Lowkey Vault using Docker command
      run: |
        cd docker
        sh example.sh
        sleep 5
        docker ps
    - name: Test with go
      run: |
        go clean -testcache
        go test ./test -v
    - name: Stop container with command
      if: always()
      run: |
        docker stop lowkey-docker
