
name: Docker test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        module: [ shell, compose, multiarch ]
        include:
          - module: shell
            name: Docker with a shell script
            path: docker
            tool: docker
            stop: docker stop lowkey-docker
          - module: compose
            name: Docker Compose with the classic image
            path: docker-compose
            tool: docker-compose
            stop: docker-compose down
          - module: multiarch
            name: Docker Compose with the multiarch image
            path: docker-compose-multiarch
            tool: docker-compose
            stop: docker-compose down
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.18.2'
    - name: Start Lowkey Vault using Docker compose
      if: ${{ matrix.tool == 'docker-compose' }}
      run: |
        cd ${{ matrix.path }}
        echo "Running ${{ matrix.name }}"
        docker-compose up -d
        sleep 5
        docker ps
    - name: Start Lowkey Vault using Docker command
      if: ${{ matrix.tool == 'docker' }}
      run: |
        cd ${{ matrix.path }}
        echo "Running ${{ matrix.name }}" 
        sh example.sh
        sleep 5
        docker ps
    - name: Test with go
      run: |
        go clean -testcache
        go test ./test -v
    - name: Stop container
      if: always()
      run: |
        cd ${{ matrix.path }}
        ${{ matrix.stop }}
